### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by rabble** [evbogue/minbase#4]
```
17:29 $ npm run build
npm start

> minbase@3.5.1 build /Users/rabble/code/ssb/minbase
> node scripts/style.js && mkdir -p build && browserify index.js | indexhtmlify > build/index.html

✔ ~/code/ssb/minbase [master|✔] 
17:29 $ npm start

> minbase@3.5.1 start /Users/rabble/code/ssb/minbase
> node bin server

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'decent-ssb/config/inject'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rabble/code/ssb/minbase/bin.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minbase@3.5.1 start: `node bin server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minbase@3.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rabble/.npm/_logs/2018-05-09T00_29_10_891Z-debug.log



0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle minbase@3.5.1~prestart: minbase@3.5.1
6 info lifecycle minbase@3.5.1~start: minbase@3.5.1
7 verbose lifecycle minbase@3.5.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle minbase@3.5.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rabble/code/ssb/minbase/node_modules/.bin:/Users/rabble/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle minbase@3.5.1~start: CWD: /Users/rabble/code/ssb/minbase
10 silly lifecycle minbase@3.5.1~start: Args: [ '-c', 'node bin server' ]
11 silly lifecycle minbase@3.5.1~start: Returned: code: 1  signal: null
12 info lifecycle minbase@3.5.1~start: Failed to exec start script
13 verbose stack Error: minbase@3.5.1 start: `node bin server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid minbase@3.5.1
15 verbose cwd /Users/rabble/code/ssb/minbase
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error minbase@3.5.1 start: `node bin server`
22 error Exit status 1
23 error Failed at the minbase@3.5.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Any clues as to what's causing this to fail? Is it my fault or minbase or ssb?

**Comment by evbogue** [comment]
@rabble I might have forgotten to publish the `decent-ssb` version that was in the package-lock file. Try again with: https://github.com/evbogue/minbase/commit/88dc35cb78bd06c7f3c4724359a0572eb6179ee4

**Comment by evbogue** [comment]
Closing because this is resolved.
