### ISSUE TITLE
setting headers too late

### ISSUE THREAD

**Issue by kevinw** [evbogue/minbase#5]
After installing on my raspberry pi and running the server, I get an error about setting headers too late:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at /home/pi/Downloads/minbase/node_modules/decent-ssb/plugins/ws/json-api.js:23:11
    at handle (/home/pi/Downloads/minbase/node_modules/stack/stack.js:11:9)
    at /home/pi/Downloads/minbase/node_modules/stack/stack.js:13:11
    at /home/pi/Downloads/minbase/node_modules/emoji-server/index.js:21:7
    at handle (/home/pi/Downloads/minbase/node_modules/stack/stack.js:11:9)
    at /home/pi/Downloads/minbase/node_modules/stack/stack.js:13:11
    at /home/pi/Downloads/minbase/bin.js:48:16
    at /home/pi/Downloads/minbase/node_modules/decent-ssb/plugins/ws/json-api.js:18:40
```

My setup is:

```
$ node --version
v9.11.1

$ npm --version
6.0.1
```

**Comment by evbogue** [comment]
@kevinw Yes! This needs to be fixed. This issue is also over here: https://github.com/evbogue/decent/issues/11

The root of the issue is the interaction between:
https://github.com/evbogue/decent/blob/master/bin.js#L35-L51
and
https://github.com/evbogue/decent/blob/master/plugins/ws/json-api.js#L22-L28

**Comment by evbogue** [comment]
@kevinw Fixed in 53b9195f321f33b8700ff509f1a3a2a7b9e25001

I ended up modifying my already modified `ssb-ws` so that it wouldn't throw these errors anymore. Check out https://github.com/evbogue/decent-ws for details.

Let me know if this works for you!
